#!/bin/bash
# OpenSmelt — Interactive first-time setup
# Generates .env with secure secrets and walks you through configuration
set -e

echo "=== OpenSmelt Setup ==="
echo ""

if [ -f .env ]; then
    echo "WARNING: .env already exists."
    read -p "Overwrite? [y/N] " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Keeping existing .env. Run 'docker compose up -d' to start."
        exit 0
    fi
fi

# Check prerequisites
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker not found. Install Docker first: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "ERROR: Docker Compose not found. Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo "Prerequisites OK (Docker + Docker Compose found)"
echo ""

# Generate secrets
MEMENTO_KEY=$(openssl rand -hex 32)
PG_PASS=$(openssl rand -hex 32)

# Ask for GitHub PAT
echo "--- GitHub Personal Access Token ---"
echo "Required for the github-mcp backend."
echo "Create one at: https://github.com/settings/tokens"
echo "Scopes needed: repo, read:org (or use a fine-grained token)"
echo ""
read -p "GitHub PAT (or press Enter to skip): " GITHUB_PAT
GITHUB_PAT=${GITHUB_PAT:-ghp_your_token_here}

# Ask for optional Signal config
echo ""
echo "--- Signal Messaging (optional) ---"
echo "Requires a running Signal REST API (https://github.com/bbernhard/signal-cli-rest-api)"
echo ""
read -p "Signal API URL (or press Enter to skip): " SIGNAL_URL

SIGNAL_CONFIG=""
if [ -n "$SIGNAL_URL" ]; then
    read -p "Signal bot phone number (e.g., +15550001234): " SIGNAL_BOT
    read -p "Signal recipient phone number (e.g., +15550005678): " SIGNAL_RECIP
    SIGNAL_CONFIG="SIGNAL_API_URL=${SIGNAL_URL}
SIGNAL_BOT_NUMBER=${SIGNAL_BOT}
SIGNAL_SENDER=${SIGNAL_BOT}
SIGNAL_RECIPIENT=${SIGNAL_RECIP}"
else
    SIGNAL_CONFIG="# SIGNAL_API_URL=
# SIGNAL_BOT_NUMBER=
# SIGNAL_SENDER=
# SIGNAL_RECIPIENT="
fi

# Write .env
cat > .env << EOF
# OpenSmelt Configuration — generated by setup.sh
# Edit as needed. Re-run ./setup.sh to regenerate.

# === Core (auto-generated) ===
MEMENTO_ACCESS_KEY=${MEMENTO_KEY}
POSTGRES_PASSWORD=${PG_PASS}

# === GitHub ===
GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PAT}

# === OpenAI (optional — for Memento semantic search) ===
# OPENAI_API_KEY=

# === Signal Messaging (optional) ===
${SIGNAL_CONFIG}

# === Ollama (optional — auto-detects host) ===
# OLLAMA_HOST=http://host.docker.internal:11434

# === Cloudflare (optional) ===
# CLOUDFLARE_API_TOKEN=
# CLOUDFLARE_ACCOUNT_ID=

# === Domain (for Caddy reverse proxy) ===
# DOMAIN=localhost

# === Gateway ===
GATEWAY_PORT=9000
EOF

echo ""
echo "=== .env created ==="
echo ""
echo "Next steps:"
echo "  1. docker compose up -d          # start all services"
echo "  2. ./scripts/test-gateway.sh     # verify health"
echo ""
echo "To connect Claude Code, add to your MCP config:"
echo '  {"mcpServers": {"opensmelt": {"type": "http", "url": "http://localhost:9000/mcp"}}}'
